// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.30.0
// 	protoc        v3.20.3
// source: pkg/model/apo_apps.proto

package model

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type QueryMonitedAppRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	NodeIp    string `protobuf:"bytes,1,opt,name=nodeIp,proto3" json:"nodeIp,omitempty"`
	NodeName  string `protobuf:"bytes,2,opt,name=nodeName,proto3" json:"nodeName,omitempty"`
	ClusterId string `protobuf:"bytes,3,opt,name=clusterId,proto3" json:"clusterId,omitempty"`
}

func (x *QueryMonitedAppRequest) Reset() {
	*x = QueryMonitedAppRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_model_apo_apps_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QueryMonitedAppRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryMonitedAppRequest) ProtoMessage() {}

func (x *QueryMonitedAppRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_model_apo_apps_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryMonitedAppRequest.ProtoReflect.Descriptor instead.
func (*QueryMonitedAppRequest) Descriptor() ([]byte, []int) {
	return file_pkg_model_apo_apps_proto_rawDescGZIP(), []int{0}
}

func (x *QueryMonitedAppRequest) GetNodeIp() string {
	if x != nil {
		return x.NodeIp
	}
	return ""
}

func (x *QueryMonitedAppRequest) GetNodeName() string {
	if x != nil {
		return x.NodeName
	}
	return ""
}

func (x *QueryMonitedAppRequest) GetClusterId() string {
	if x != nil {
		return x.ClusterId
	}
	return ""
}

type QueryMonitedAppResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Datas []*QueryMonitedAppData `protobuf:"bytes,1,rep,name=datas,proto3" json:"datas,omitempty"`
}

func (x *QueryMonitedAppResponse) Reset() {
	*x = QueryMonitedAppResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_model_apo_apps_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QueryMonitedAppResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryMonitedAppResponse) ProtoMessage() {}

func (x *QueryMonitedAppResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_model_apo_apps_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryMonitedAppResponse.ProtoReflect.Descriptor instead.
func (*QueryMonitedAppResponse) Descriptor() ([]byte, []int) {
	return file_pkg_model_apo_apps_proto_rawDescGZIP(), []int{1}
}

func (x *QueryMonitedAppResponse) GetDatas() []*QueryMonitedAppData {
	if x != nil {
		return x.Datas
	}
	return nil
}

type QueryMonitedAppData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Source      string `protobuf:"bytes,1,opt,name=source,proto3" json:"source,omitempty"`
	ServiceId   string `protobuf:"bytes,2,opt,name=serviceId,proto3" json:"serviceId,omitempty"`
	ServiceName string `protobuf:"bytes,3,opt,name=serviceName,proto3" json:"serviceName,omitempty"`
	StartTime   uint64 `protobuf:"varint,4,opt,name=startTime,proto3" json:"startTime,omitempty"`
	HostPid     uint32 `protobuf:"varint,5,opt,name=hostPid,proto3" json:"hostPid,omitempty"`
	ContainerId string `protobuf:"bytes,6,opt,name=containerId,proto3" json:"containerId,omitempty"`
	PodName     string `protobuf:"bytes,7,opt,name=podName,proto3" json:"podName,omitempty"`
}

func (x *QueryMonitedAppData) Reset() {
	*x = QueryMonitedAppData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_model_apo_apps_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QueryMonitedAppData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryMonitedAppData) ProtoMessage() {}

func (x *QueryMonitedAppData) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_model_apo_apps_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryMonitedAppData.ProtoReflect.Descriptor instead.
func (*QueryMonitedAppData) Descriptor() ([]byte, []int) {
	return file_pkg_model_apo_apps_proto_rawDescGZIP(), []int{2}
}

func (x *QueryMonitedAppData) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *QueryMonitedAppData) GetServiceId() string {
	if x != nil {
		return x.ServiceId
	}
	return ""
}

func (x *QueryMonitedAppData) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

func (x *QueryMonitedAppData) GetStartTime() uint64 {
	if x != nil {
		return x.StartTime
	}
	return 0
}

func (x *QueryMonitedAppData) GetHostPid() uint32 {
	if x != nil {
		return x.HostPid
	}
	return 0
}

func (x *QueryMonitedAppData) GetContainerId() string {
	if x != nil {
		return x.ContainerId
	}
	return ""
}

func (x *QueryMonitedAppData) GetPodName() string {
	if x != nil {
		return x.PodName
	}
	return ""
}

type QueryActiveAppRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	NodeIp     string            `protobuf:"bytes,1,opt,name=nodeIp,proto3" json:"nodeIp,omitempty"`
	NodeName   string            `protobuf:"bytes,2,opt,name=nodeName,proto3" json:"nodeName,omitempty"`
	ActiveApps []*QueryActiveApp `protobuf:"bytes,3,rep,name=activeApps,proto3" json:"activeApps,omitempty"`
	DeadApps   []*QueryActiveApp `protobuf:"bytes,4,rep,name=deadApps,proto3" json:"deadApps,omitempty"`
}

func (x *QueryActiveAppRequest) Reset() {
	*x = QueryActiveAppRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_model_apo_apps_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QueryActiveAppRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryActiveAppRequest) ProtoMessage() {}

func (x *QueryActiveAppRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_model_apo_apps_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryActiveAppRequest.ProtoReflect.Descriptor instead.
func (*QueryActiveAppRequest) Descriptor() ([]byte, []int) {
	return file_pkg_model_apo_apps_proto_rawDescGZIP(), []int{3}
}

func (x *QueryActiveAppRequest) GetNodeIp() string {
	if x != nil {
		return x.NodeIp
	}
	return ""
}

func (x *QueryActiveAppRequest) GetNodeName() string {
	if x != nil {
		return x.NodeName
	}
	return ""
}

func (x *QueryActiveAppRequest) GetActiveApps() []*QueryActiveApp {
	if x != nil {
		return x.ActiveApps
	}
	return nil
}

func (x *QueryActiveAppRequest) GetDeadApps() []*QueryActiveApp {
	if x != nil {
		return x.DeadApps
	}
	return nil
}

type QueryActiveAppResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Datas []*QueryActiveApp `protobuf:"bytes,1,rep,name=datas,proto3" json:"datas,omitempty"`
}

func (x *QueryActiveAppResponse) Reset() {
	*x = QueryActiveAppResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_model_apo_apps_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QueryActiveAppResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryActiveAppResponse) ProtoMessage() {}

func (x *QueryActiveAppResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_model_apo_apps_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryActiveAppResponse.ProtoReflect.Descriptor instead.
func (*QueryActiveAppResponse) Descriptor() ([]byte, []int) {
	return file_pkg_model_apo_apps_proto_rawDescGZIP(), []int{4}
}

func (x *QueryActiveAppResponse) GetDatas() []*QueryActiveApp {
	if x != nil {
		return x.Datas
	}
	return nil
}

type QueryActiveApp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Pid       uint32 `protobuf:"varint,1,opt,name=pid,proto3" json:"pid,omitempty"`
	StartTime uint64 `protobuf:"varint,2,opt,name=startTime,proto3" json:"startTime,omitempty"`
}

func (x *QueryActiveApp) Reset() {
	*x = QueryActiveApp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_model_apo_apps_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QueryActiveApp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryActiveApp) ProtoMessage() {}

func (x *QueryActiveApp) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_model_apo_apps_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryActiveApp.ProtoReflect.Descriptor instead.
func (*QueryActiveApp) Descriptor() ([]byte, []int) {
	return file_pkg_model_apo_apps_proto_rawDescGZIP(), []int{5}
}

func (x *QueryActiveApp) GetPid() uint32 {
	if x != nil {
		return x.Pid
	}
	return 0
}

func (x *QueryActiveApp) GetStartTime() uint64 {
	if x != nil {
		return x.StartTime
	}
	return 0
}

var File_pkg_model_apo_apps_proto protoreflect.FileDescriptor

var file_pkg_model_apo_apps_proto_rawDesc = []byte{
	0x0a, 0x18, 0x70, 0x6b, 0x67, 0x2f, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x2f, 0x61, 0x70, 0x6f, 0x5f,
	0x61, 0x70, 0x70, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x08, 0x6b, 0x69, 0x6e, 0x64,
	0x6c, 0x69, 0x6e, 0x67, 0x22, 0x6a, 0x0a, 0x16, 0x51, 0x75, 0x65, 0x72, 0x79, 0x4d, 0x6f, 0x6e,
	0x69, 0x74, 0x65, 0x64, 0x41, 0x70, 0x70, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16,
	0x0a, 0x06, 0x6e, 0x6f, 0x64, 0x65, 0x49, 0x70, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06,
	0x6e, 0x6f, 0x64, 0x65, 0x49, 0x70, 0x12, 0x1a, 0x0a, 0x08, 0x6e, 0x6f, 0x64, 0x65, 0x4e, 0x61,
	0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x6e, 0x6f, 0x64, 0x65, 0x4e, 0x61,
	0x6d, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x63, 0x6c, 0x75, 0x73, 0x74, 0x65, 0x72, 0x49, 0x64, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x63, 0x6c, 0x75, 0x73, 0x74, 0x65, 0x72, 0x49, 0x64,
	0x22, 0x4e, 0x0a, 0x17, 0x51, 0x75, 0x65, 0x72, 0x79, 0x4d, 0x6f, 0x6e, 0x69, 0x74, 0x65, 0x64,
	0x41, 0x70, 0x70, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x33, 0x0a, 0x05, 0x64,
	0x61, 0x74, 0x61, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1d, 0x2e, 0x6b, 0x69, 0x6e,
	0x64, 0x6c, 0x69, 0x6e, 0x67, 0x2e, 0x51, 0x75, 0x65, 0x72, 0x79, 0x4d, 0x6f, 0x6e, 0x69, 0x74,
	0x65, 0x64, 0x41, 0x70, 0x70, 0x44, 0x61, 0x74, 0x61, 0x52, 0x05, 0x64, 0x61, 0x74, 0x61, 0x73,
	0x22, 0xe1, 0x01, 0x0a, 0x13, 0x51, 0x75, 0x65, 0x72, 0x79, 0x4d, 0x6f, 0x6e, 0x69, 0x74, 0x65,
	0x64, 0x41, 0x70, 0x70, 0x44, 0x61, 0x74, 0x61, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x6f, 0x75, 0x72,
	0x63, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65,
	0x12, 0x1c, 0x0a, 0x09, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x49, 0x64, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x09, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x49, 0x64, 0x12, 0x20,
	0x0a, 0x0b, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0b, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x4e, 0x61, 0x6d, 0x65,
	0x12, 0x1c, 0x0a, 0x09, 0x73, 0x74, 0x61, 0x72, 0x74, 0x54, 0x69, 0x6d, 0x65, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x04, 0x52, 0x09, 0x73, 0x74, 0x61, 0x72, 0x74, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x18,
	0x0a, 0x07, 0x68, 0x6f, 0x73, 0x74, 0x50, 0x69, 0x64, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0d, 0x52,
	0x07, 0x68, 0x6f, 0x73, 0x74, 0x50, 0x69, 0x64, 0x12, 0x20, 0x0a, 0x0b, 0x63, 0x6f, 0x6e, 0x74,
	0x61, 0x69, 0x6e, 0x65, 0x72, 0x49, 0x64, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x63,
	0x6f, 0x6e, 0x74, 0x61, 0x69, 0x6e, 0x65, 0x72, 0x49, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x70, 0x6f,
	0x64, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x70, 0x6f, 0x64,
	0x4e, 0x61, 0x6d, 0x65, 0x22, 0xbb, 0x01, 0x0a, 0x15, 0x51, 0x75, 0x65, 0x72, 0x79, 0x41, 0x63,
	0x74, 0x69, 0x76, 0x65, 0x41, 0x70, 0x70, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16,
	0x0a, 0x06, 0x6e, 0x6f, 0x64, 0x65, 0x49, 0x70, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06,
	0x6e, 0x6f, 0x64, 0x65, 0x49, 0x70, 0x12, 0x1a, 0x0a, 0x08, 0x6e, 0x6f, 0x64, 0x65, 0x4e, 0x61,
	0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x6e, 0x6f, 0x64, 0x65, 0x4e, 0x61,
	0x6d, 0x65, 0x12, 0x38, 0x0a, 0x0a, 0x61, 0x63, 0x74, 0x69, 0x76, 0x65, 0x41, 0x70, 0x70, 0x73,
	0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x6b, 0x69, 0x6e, 0x64, 0x6c, 0x69, 0x6e,
	0x67, 0x2e, 0x51, 0x75, 0x65, 0x72, 0x79, 0x41, 0x63, 0x74, 0x69, 0x76, 0x65, 0x41, 0x70, 0x70,
	0x52, 0x0a, 0x61, 0x63, 0x74, 0x69, 0x76, 0x65, 0x41, 0x70, 0x70, 0x73, 0x12, 0x34, 0x0a, 0x08,
	0x64, 0x65, 0x61, 0x64, 0x41, 0x70, 0x70, 0x73, 0x18, 0x04, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x18,
	0x2e, 0x6b, 0x69, 0x6e, 0x64, 0x6c, 0x69, 0x6e, 0x67, 0x2e, 0x51, 0x75, 0x65, 0x72, 0x79, 0x41,
	0x63, 0x74, 0x69, 0x76, 0x65, 0x41, 0x70, 0x70, 0x52, 0x08, 0x64, 0x65, 0x61, 0x64, 0x41, 0x70,
	0x70, 0x73, 0x22, 0x48, 0x0a, 0x16, 0x51, 0x75, 0x65, 0x72, 0x79, 0x41, 0x63, 0x74, 0x69, 0x76,
	0x65, 0x41, 0x70, 0x70, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2e, 0x0a, 0x05,
	0x64, 0x61, 0x74, 0x61, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x6b, 0x69,
	0x6e, 0x64, 0x6c, 0x69, 0x6e, 0x67, 0x2e, 0x51, 0x75, 0x65, 0x72, 0x79, 0x41, 0x63, 0x74, 0x69,
	0x76, 0x65, 0x41, 0x70, 0x70, 0x52, 0x05, 0x64, 0x61, 0x74, 0x61, 0x73, 0x22, 0x40, 0x0a, 0x0e,
	0x51, 0x75, 0x65, 0x72, 0x79, 0x41, 0x63, 0x74, 0x69, 0x76, 0x65, 0x41, 0x70, 0x70, 0x12, 0x10,
	0x0a, 0x03, 0x70, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x03, 0x70, 0x69, 0x64,
	0x12, 0x1c, 0x0a, 0x09, 0x73, 0x74, 0x61, 0x72, 0x74, 0x54, 0x69, 0x6d, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x04, 0x52, 0x09, 0x73, 0x74, 0x61, 0x72, 0x74, 0x54, 0x69, 0x6d, 0x65, 0x32, 0xbb,
	0x01, 0x0a, 0x0a, 0x41, 0x70, 0x70, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x57, 0x0a,
	0x10, 0x51, 0x75, 0x65, 0x72, 0x79, 0x4d, 0x6f, 0x6e, 0x69, 0x74, 0x65, 0x64, 0x41, 0x70, 0x70,
	0x73, 0x12, 0x20, 0x2e, 0x6b, 0x69, 0x6e, 0x64, 0x6c, 0x69, 0x6e, 0x67, 0x2e, 0x51, 0x75, 0x65,
	0x72, 0x79, 0x4d, 0x6f, 0x6e, 0x69, 0x74, 0x65, 0x64, 0x41, 0x70, 0x70, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x21, 0x2e, 0x6b, 0x69, 0x6e, 0x64, 0x6c, 0x69, 0x6e, 0x67, 0x2e, 0x51,
	0x75, 0x65, 0x72, 0x79, 0x4d, 0x6f, 0x6e, 0x69, 0x74, 0x65, 0x64, 0x41, 0x70, 0x70, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x54, 0x0a, 0x0f, 0x51, 0x75, 0x65, 0x72, 0x79, 0x41,
	0x63, 0x74, 0x69, 0x76, 0x65, 0x41, 0x70, 0x70, 0x73, 0x12, 0x1f, 0x2e, 0x6b, 0x69, 0x6e, 0x64,
	0x6c, 0x69, 0x6e, 0x67, 0x2e, 0x51, 0x75, 0x65, 0x72, 0x79, 0x41, 0x63, 0x74, 0x69, 0x76, 0x65,
	0x41, 0x70, 0x70, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x20, 0x2e, 0x6b, 0x69, 0x6e,
	0x64, 0x6c, 0x69, 0x6e, 0x67, 0x2e, 0x51, 0x75, 0x65, 0x72, 0x79, 0x41, 0x63, 0x74, 0x69, 0x76,
	0x65, 0x41, 0x70, 0x70, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x09, 0x5a, 0x07,
	0x2e, 0x3b, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_pkg_model_apo_apps_proto_rawDescOnce sync.Once
	file_pkg_model_apo_apps_proto_rawDescData = file_pkg_model_apo_apps_proto_rawDesc
)

func file_pkg_model_apo_apps_proto_rawDescGZIP() []byte {
	file_pkg_model_apo_apps_proto_rawDescOnce.Do(func() {
		file_pkg_model_apo_apps_proto_rawDescData = protoimpl.X.CompressGZIP(file_pkg_model_apo_apps_proto_rawDescData)
	})
	return file_pkg_model_apo_apps_proto_rawDescData
}

var file_pkg_model_apo_apps_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_pkg_model_apo_apps_proto_goTypes = []interface{}{
	(*QueryMonitedAppRequest)(nil),  // 0: kindling.QueryMonitedAppRequest
	(*QueryMonitedAppResponse)(nil), // 1: kindling.QueryMonitedAppResponse
	(*QueryMonitedAppData)(nil),     // 2: kindling.QueryMonitedAppData
	(*QueryActiveAppRequest)(nil),   // 3: kindling.QueryActiveAppRequest
	(*QueryActiveAppResponse)(nil),  // 4: kindling.QueryActiveAppResponse
	(*QueryActiveApp)(nil),          // 5: kindling.QueryActiveApp
}
var file_pkg_model_apo_apps_proto_depIdxs = []int32{
	2, // 0: kindling.QueryMonitedAppResponse.datas:type_name -> kindling.QueryMonitedAppData
	5, // 1: kindling.QueryActiveAppRequest.activeApps:type_name -> kindling.QueryActiveApp
	5, // 2: kindling.QueryActiveAppRequest.deadApps:type_name -> kindling.QueryActiveApp
	5, // 3: kindling.QueryActiveAppResponse.datas:type_name -> kindling.QueryActiveApp
	0, // 4: kindling.AppService.QueryMonitedApps:input_type -> kindling.QueryMonitedAppRequest
	3, // 5: kindling.AppService.QueryActiveApps:input_type -> kindling.QueryActiveAppRequest
	1, // 6: kindling.AppService.QueryMonitedApps:output_type -> kindling.QueryMonitedAppResponse
	4, // 7: kindling.AppService.QueryActiveApps:output_type -> kindling.QueryActiveAppResponse
	6, // [6:8] is the sub-list for method output_type
	4, // [4:6] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_pkg_model_apo_apps_proto_init() }
func file_pkg_model_apo_apps_proto_init() {
	if File_pkg_model_apo_apps_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_pkg_model_apo_apps_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*QueryMonitedAppRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_model_apo_apps_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*QueryMonitedAppResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_model_apo_apps_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*QueryMonitedAppData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_model_apo_apps_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*QueryActiveAppRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_model_apo_apps_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*QueryActiveAppResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_model_apo_apps_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*QueryActiveApp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pkg_model_apo_apps_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_model_apo_apps_proto_goTypes,
		DependencyIndexes: file_pkg_model_apo_apps_proto_depIdxs,
		MessageInfos:      file_pkg_model_apo_apps_proto_msgTypes,
	}.Build()
	File_pkg_model_apo_apps_proto = out.File
	file_pkg_model_apo_apps_proto_rawDesc = nil
	file_pkg_model_apo_apps_proto_goTypes = nil
	file_pkg_model_apo_apps_proto_depIdxs = nil
}
