// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.9
// source: apo_agent_monitor_server.proto

package model

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AgentMonitorRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Iud           string `protobuf:"bytes,1,opt,name=iud,proto3" json:"iud,omitempty"`
	KernelVersion string `protobuf:"bytes,2,opt,name=kernel_version,json=kernelVersion,proto3" json:"kernel_version,omitempty"`
	Arch          string `protobuf:"bytes,3,opt,name=arch,proto3" json:"arch,omitempty"`
	EvtNum        uint64 `protobuf:"varint,4,opt,name=evt_num,json=evtNum,proto3" json:"evt_num,omitempty"`
	CpuEvtNum     uint64 `protobuf:"varint,5,opt,name=cpu_evt_num,json=cpuEvtNum,proto3" json:"cpu_evt_num,omitempty"`
	TxEvtNum      uint64 `protobuf:"varint,6,opt,name=tx_evt_num,json=txEvtNum,proto3" json:"tx_evt_num,omitempty"`
	MemUsage      uint64 `protobuf:"varint,7,opt,name=mem_usage,json=memUsage,proto3" json:"mem_usage,omitempty"`
	CpuUsage      uint64 `protobuf:"varint,8,opt,name=cpu_usage,json=cpuUsage,proto3" json:"cpu_usage,omitempty"`
}

func (x *AgentMonitorRequest) Reset() {
	*x = AgentMonitorRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_apo_agent_monitor_server_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AgentMonitorRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentMonitorRequest) ProtoMessage() {}

func (x *AgentMonitorRequest) ProtoReflect() protoreflect.Message {
	mi := &file_apo_agent_monitor_server_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentMonitorRequest.ProtoReflect.Descriptor instead.
func (*AgentMonitorRequest) Descriptor() ([]byte, []int) {
	return file_apo_agent_monitor_server_proto_rawDescGZIP(), []int{0}
}

func (x *AgentMonitorRequest) GetIud() string {
	if x != nil {
		return x.Iud
	}
	return ""
}

func (x *AgentMonitorRequest) GetKernelVersion() string {
	if x != nil {
		return x.KernelVersion
	}
	return ""
}

func (x *AgentMonitorRequest) GetArch() string {
	if x != nil {
		return x.Arch
	}
	return ""
}

func (x *AgentMonitorRequest) GetEvtNum() uint64 {
	if x != nil {
		return x.EvtNum
	}
	return 0
}

func (x *AgentMonitorRequest) GetCpuEvtNum() uint64 {
	if x != nil {
		return x.CpuEvtNum
	}
	return 0
}

func (x *AgentMonitorRequest) GetTxEvtNum() uint64 {
	if x != nil {
		return x.TxEvtNum
	}
	return 0
}

func (x *AgentMonitorRequest) GetMemUsage() uint64 {
	if x != nil {
		return x.MemUsage
	}
	return 0
}

func (x *AgentMonitorRequest) GetCpuUsage() uint64 {
	if x != nil {
		return x.CpuUsage
	}
	return 0
}

type AgentMonitorResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	IsOk string `protobuf:"bytes,1,opt,name=is_ok,json=isOk,proto3" json:"is_ok,omitempty"`
}

func (x *AgentMonitorResponse) Reset() {
	*x = AgentMonitorResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_apo_agent_monitor_server_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AgentMonitorResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentMonitorResponse) ProtoMessage() {}

func (x *AgentMonitorResponse) ProtoReflect() protoreflect.Message {
	mi := &file_apo_agent_monitor_server_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentMonitorResponse.ProtoReflect.Descriptor instead.
func (*AgentMonitorResponse) Descriptor() ([]byte, []int) {
	return file_apo_agent_monitor_server_proto_rawDescGZIP(), []int{1}
}

func (x *AgentMonitorResponse) GetIsOk() string {
	if x != nil {
		return x.IsOk
	}
	return ""
}

var File_apo_agent_monitor_server_proto protoreflect.FileDescriptor

var file_apo_agent_monitor_server_proto_rawDesc = []byte{
	0x0a, 0x1e, 0x61, 0x70, 0x6f, 0x5f, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x5f, 0x6d, 0x6f, 0x6e, 0x69,
	0x74, 0x6f, 0x72, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x08, 0x6b, 0x69, 0x6e, 0x64, 0x6c, 0x69, 0x6e, 0x67, 0x22, 0xf3, 0x01, 0x0a, 0x13, 0x41,
	0x67, 0x65, 0x6e, 0x74, 0x4d, 0x6f, 0x6e, 0x69, 0x74, 0x6f, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x69, 0x75, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x03, 0x69, 0x75, 0x64, 0x12, 0x25, 0x0a, 0x0e, 0x6b, 0x65, 0x72, 0x6e, 0x65, 0x6c, 0x5f, 0x76,
	0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x6b, 0x65,
	0x72, 0x6e, 0x65, 0x6c, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x12, 0x0a, 0x04, 0x61,
	0x72, 0x63, 0x68, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x61, 0x72, 0x63, 0x68, 0x12,
	0x17, 0x0a, 0x07, 0x65, 0x76, 0x74, 0x5f, 0x6e, 0x75, 0x6d, 0x18, 0x04, 0x20, 0x01, 0x28, 0x04,
	0x52, 0x06, 0x65, 0x76, 0x74, 0x4e, 0x75, 0x6d, 0x12, 0x1e, 0x0a, 0x0b, 0x63, 0x70, 0x75, 0x5f,
	0x65, 0x76, 0x74, 0x5f, 0x6e, 0x75, 0x6d, 0x18, 0x05, 0x20, 0x01, 0x28, 0x04, 0x52, 0x09, 0x63,
	0x70, 0x75, 0x45, 0x76, 0x74, 0x4e, 0x75, 0x6d, 0x12, 0x1c, 0x0a, 0x0a, 0x74, 0x78, 0x5f, 0x65,
	0x76, 0x74, 0x5f, 0x6e, 0x75, 0x6d, 0x18, 0x06, 0x20, 0x01, 0x28, 0x04, 0x52, 0x08, 0x74, 0x78,
	0x45, 0x76, 0x74, 0x4e, 0x75, 0x6d, 0x12, 0x1b, 0x0a, 0x09, 0x6d, 0x65, 0x6d, 0x5f, 0x75, 0x73,
	0x61, 0x67, 0x65, 0x18, 0x07, 0x20, 0x01, 0x28, 0x04, 0x52, 0x08, 0x6d, 0x65, 0x6d, 0x55, 0x73,
	0x61, 0x67, 0x65, 0x12, 0x1b, 0x0a, 0x09, 0x63, 0x70, 0x75, 0x5f, 0x75, 0x73, 0x61, 0x67, 0x65,
	0x18, 0x08, 0x20, 0x01, 0x28, 0x04, 0x52, 0x08, 0x63, 0x70, 0x75, 0x55, 0x73, 0x61, 0x67, 0x65,
	0x22, 0x2b, 0x0a, 0x14, 0x41, 0x67, 0x65, 0x6e, 0x74, 0x4d, 0x6f, 0x6e, 0x69, 0x74, 0x6f, 0x72,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x13, 0x0a, 0x05, 0x69, 0x73, 0x5f, 0x6f,
	0x6b, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x69, 0x73, 0x4f, 0x6b, 0x32, 0x6e, 0x0a,
	0x13, 0x41, 0x67, 0x65, 0x6e, 0x74, 0x4d, 0x6f, 0x6e, 0x69, 0x74, 0x6f, 0x72, 0x53, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x12, 0x57, 0x0a, 0x16, 0x53, 0x65, 0x6e, 0x64, 0x41, 0x67, 0x65, 0x6e,
	0x74, 0x4d, 0x6f, 0x6e, 0x69, 0x74, 0x6f, 0x72, 0x4d, 0x65, 0x74, 0x72, 0x69, 0x63, 0x12, 0x1d,
	0x2e, 0x6b, 0x69, 0x6e, 0x64, 0x6c, 0x69, 0x6e, 0x67, 0x2e, 0x41, 0x67, 0x65, 0x6e, 0x74, 0x4d,
	0x6f, 0x6e, 0x69, 0x74, 0x6f, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1e, 0x2e,
	0x6b, 0x69, 0x6e, 0x64, 0x6c, 0x69, 0x6e, 0x67, 0x2e, 0x41, 0x67, 0x65, 0x6e, 0x74, 0x4d, 0x6f,
	0x6e, 0x69, 0x74, 0x6f, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x09, 0x5a,
	0x07, 0x2e, 0x3b, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_apo_agent_monitor_server_proto_rawDescOnce sync.Once
	file_apo_agent_monitor_server_proto_rawDescData = file_apo_agent_monitor_server_proto_rawDesc
)

func file_apo_agent_monitor_server_proto_rawDescGZIP() []byte {
	file_apo_agent_monitor_server_proto_rawDescOnce.Do(func() {
		file_apo_agent_monitor_server_proto_rawDescData = protoimpl.X.CompressGZIP(file_apo_agent_monitor_server_proto_rawDescData)
	})
	return file_apo_agent_monitor_server_proto_rawDescData
}

var file_apo_agent_monitor_server_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_apo_agent_monitor_server_proto_goTypes = []interface{}{
	(*AgentMonitorRequest)(nil),  // 0: kindling.AgentMonitorRequest
	(*AgentMonitorResponse)(nil), // 1: kindling.AgentMonitorResponse
}
var file_apo_agent_monitor_server_proto_depIdxs = []int32{
	0, // 0: kindling.AgentMonitorService.SendAgentMonitorMetric:input_type -> kindling.AgentMonitorRequest
	1, // 1: kindling.AgentMonitorService.SendAgentMonitorMetric:output_type -> kindling.AgentMonitorResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_apo_agent_monitor_server_proto_init() }
func file_apo_agent_monitor_server_proto_init() {
	if File_apo_agent_monitor_server_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_apo_agent_monitor_server_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AgentMonitorRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_apo_agent_monitor_server_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AgentMonitorResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_apo_agent_monitor_server_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_apo_agent_monitor_server_proto_goTypes,
		DependencyIndexes: file_apo_agent_monitor_server_proto_depIdxs,
		MessageInfos:      file_apo_agent_monitor_server_proto_msgTypes,
	}.Build()
	File_apo_agent_monitor_server_proto = out.File
	file_apo_agent_monitor_server_proto_rawDesc = nil
	file_apo_agent_monitor_server_proto_goTypes = nil
	file_apo_agent_monitor_server_proto_depIdxs = nil
}
